# configuration_service_components.yml
components:
  messages:
    PushToRepoBegin:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/PushToRepoBeginPayloadSchema"
    PushToRepoEnd:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/PushToRepoEndPayloadSchema" 
    PushToRepoFail:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/PushToRepoFailPayloadSchema"      
    
    CompensatePushToRepoBegin:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CompensatePushToRepoBeginPayloadSchema"      
    CompensatePushToRepoEnd:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CompensatePushToRepoEndPayloadSchema"
    CompensatePushToRepoFail:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CompensatePushToRepoFailPayloadSchema" 
    
    InferCdmBegin:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferCdmBeginPayloadSchema"      
    InferCdmEnd:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferCdmEndPayloadSchema"     

    InferCdmFail:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferCdmFailPayloadSchema"
    
    CdmToShaclBegin:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CdmToShaclBeginPayloadSchema" 
    CdmToShaclEnd:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CdmToShaclEndPayloadSchema"      
    CdmToShaclFail:
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CdmToShaclFailPayloadSchema"              

  schemas:
    PushToRepoBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    PushToRepoEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    PushToRepoFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId


    CompensatePushToRepoBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    CompensatePushToRepoEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    CompensatePushToRepoFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
          
    InferCdmBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    InferCdmEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    InferCdmFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId

    CdmToShaclBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    CdmToShaclEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    CdmToShaclFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId