# configuration_service_components.yml
components:
  messages:
    PushToRepoBegin:
      description: The SEC sends this message to push the artifacts to the configuration repository.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/PushToRepoBeginPayloadSchema"
    PushToRepoEnd:
      description: The Configuration Service confirms that it succeeded to push the artifacts to the configuration repository.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/PushToRepoEndPayloadSchema" 
    PushToRepoFail:
      description: The Configuration Service failed to push the artifacts to the configuration repository.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/PushToRepoFailPayloadSchema"      
    
    CompensatePushToRepoBegin:
      description: The SEC sends this message to compensate the push of an artifact to the configuration repository.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CompensatePushToRepoBeginPayloadSchema"      
    CompensatePushToRepoEnd:
      description: The Configuration Service confirms that it succeeded to compensate the push of an artifact to the configuration repository.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CompensatePushToRepoEndPayloadSchema"
    CompensatePushToRepoFail:
      description: The Configuration Service indicates that it failed to compensate the push of an artifact to the configuration repository.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CompensatePushToRepoFailPayloadSchema" 
    
    InferCdmBegin:
      description: The SEC sends this message to infer the CDM.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferCdmBeginPayloadSchema"      
    InferCdmEnd:
      description: The Configuration Service confirms that it succeeds.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferCdmEndPayloadSchema"     
    InferCdmFail:
      description: The Configuration Service indicates that it failed to infer the CDM ontology.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferCdmFailPayloadSchema"

    InferSkosBegin:
      description: The SEC sends this message to infer the authority table.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferSkosBeginPayloadSchema"      
    InferSkosEnd:
      description: The Configuration Service confirms that it succeeded to infer the authority table.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferSkosEndPayloadSchema"     
    InferSkosFail:
      description: The Configuration Service indicates that it failed to infer the authority table.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/InferSkosFailPayloadSchema"

    
    CdmToShaclBegin:
      description: The SEC sends this message to get the SHACL shapes from the current version of the CDM.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CdmToShaclBeginPayloadSchema" 
    CdmToShaclEnd:
      description: The Configuration Service confirms that it succeeded to generate the SHACL shapes.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CdmToShaclEndPayloadSchema"      
    CdmToShaclFail:
      description: The Configuration Service indicates that it failed to generate the new SHACL shapes.
      correlationId:
        $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/correlationIds/traceIdCorrelator"
      payload:
        $ref: "#/components/schemas/CdmToShaclFailPayloadSchema"              

  schemas:
    PushToRepoBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    PushToRepoEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    PushToRepoFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId


    CompensatePushToRepoBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    CompensatePushToRepoEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId
    CompensatePushToRepoFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema" 
      required:
      - traceId

    InferCdmBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
        sharedAreaRef: 
          description: "By processing the *.mets.xml, the Configuration Service determines the CDM source files."
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/sharedAreaRefSchema"
      required:
      - traceId
      - sharedAreaRef
    InferCdmEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    InferCdmFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId

    InferSkosBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
         sharedAreaRef: 
          description: "By processing the *.mets.xml, the Configuration Service determines the location of the NAL files."
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/sharedAreaRefSchema"
      required:
      - traceId
      - sharedAreaRef
    InferSkosEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    InferSkosFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId

    CdmToShaclBeginPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    CdmToShaclEndPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
    CdmToShaclFailPayloadSchema:
      type: object
      properties:
        traceId:
          $ref: "https://raw.githubusercontent.com/op-cellar-git/cellar-transaction/master/apis/asyncapi/shared_components/shared_components.yml#/components/schemas/traceIdSchema"
      required:
      - traceId
